import Head from "next/head"
import Image from "next/image"
import { Inter } from "next/font/google"
import styles from "@/styles/Home.module.css"
import { useQuery } from "@tanstack/react-query"

const inter = Inter({ subsets: ["latin"] })

const fetchTest = async () => {
  const response = await fetch(
    "https://tototata.azurewebsites.net/weatherforecast"
  )

  return response.json()
}

const fetchChuck = async () => {
  const response = await fetch("https://api.chucknorris.io/jokes/random")

  return response.json()
}

export default function Home() {
  const { data } = useQuery({ queryKey: ["test"], queryFn: fetchTest })
  const { data: chuck } = useQuery({ queryKey: ["chuck"], queryFn: fetchChuck })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          {JSON.stringify(data, null, 2)}
        </div>
        <div className={styles.description}>{chuck?.value}</div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}></div>
      </main>
    </>
  )
}
